sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        IA410pDCYTOsNOuIQzSbwdFU9Cy7uT1rv/KRJxtgcByzd1I38dtgwJ68tTmX3WdLHxGYkbmWYsQ6Or/6Vp1okMDmE2ZKu7Yz6pbU3+/Q8agLM7OG36c/WawTl/SXtkA098jTpBq6UGQQWHIJECQae4+9q4U9NKVANH9Jy9VkDOBOvrdcWJrBTtXbf9L70qWTdqozqoPpOhMb4JSzZb7OBzplfn0/HOpI6Oo4nLrX7kBUjc6ySuvXiupPoCDBgQG5Eu5zmCyjMojzIUw6fO5rIK47FRa6MR+wUejxpDsMYRE9VTmTNHEH3wGiru3hyf8hP05rPOcnst5OXBbgJDF4gUKfKEtNVb/rNMcuXzz3i+FrCA4roSxoqH9WrNt+FZJ0b+Z0rbyHzdQ5myAlEh+5KMCeRhe04+0umaQvuSlixXuu5AT/3bnNwrZexr8MHvF/G9d0lXDkGtbD6llnq8oUKGkBnqt04WSp3OzxVppGvFZDZRwbBFXuswAibjnQHMN0mX2TirbNZsiHGZUUmTvoSNxSylU96JREJeIA54xHoANZkkmbTjLcK10WTa8gYqABX+mi7Ms1Cm4FZWCq4rbhURP9UtfT5Yw2DJ49wCp/Whyoau3pPrSVquEN6Pz68bKmCBwmWIcSgFD68ZP6WfonHGxT9UxSBcAtu50ru8CUZKU=
    - secure: >-
        bR+XK/+F8kUrJF0ZlXdsuecWMAy7gsx1xZRlESrWONFXmgkaPiHV0aHtFH5vCICN9xYlexn9XQPwcL6fJExLIcQOlk3PbuuzDavJLbSH9ooZYb0vN0sKRb/L5KkyyeGICkY8VKiYLOwrsMBUjDqdVr6hi5ZPt27oeZpFuQJPyXGjacGQxB/NEBvm42XXtSBsCbX+2Wlv82cHm5BiXhSRp91jMpaOCQp3DZvO5mYmuGY8Hs7Im5udK0LyrbK0/OHkNOyXooi8TsHUcAWfNuit5qnI27truAr4nh8nLp1O3rhWq5tDjXGHfWHVS7cjgaIxTz+vVpIQzKxRkKCVYRT7cF3q+ly1iYrgi4Tjb+pFYO9aci6RRQd1J3sZ1QxShYTMAdFnHmZ96LAPbDNnbxgZZQj1dXtpVa7+BkxwpTJWhpd1qgAgYsvJWAwRfVN5yYaRKFuKLHLTpt3Ie5HZqdJcUZiEobdE6yo+EmNsFdLlNrusTr91UdP+DMpzlOc1S7DijKFngAF6A/x9J+74sN2dXLneFT2RWzX0QN2Qg3QL6QH7obv1usdCgm7iJk7ZOdRCiqy1bad0xGVaa2GJKob9ebIb4KZmsyLnIDvox50QnTgJX4gDb923spTv1R21VB0NXm18m7Wt1O0oErobcSsTuB2k3muAmXSfJq+BlotlXfI=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
